<?php

namespace App\Http\Requests;


class ThreadRequtest extends Request
{


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        switch($this->method())
        {
            // CREATE
            case 'POST':

                // UPDATE
            case 'PUT':
            case 'PATCH':
                {
                    return [
                        // UPDATE ROLES
                        'title'       => 'required',
                        'body' => 'required',
                        'channel_id' => 'required|exists:channels,id'
                    ];
                }
            case 'GET':
            case 'DELETE':
            default:
                {
                    return [];
                };
        }
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
